environment: "local" # "local", "dev", "prod"
repository_file: "./internal/repository/repository.db"
http_server:
  address: "localhost:8080"
  timeout: 5s
  idle_timeout: 60s
logger:
  format: "json"         # "text", "json"
  destination: "stdout"  # "stdout", "stderr", "file"
  destination_file: ""   # filename if <destination: "file">
  level: "debug"         # "debug", "info"
  add_source: false