environment: "local" # "local", "dev", "prod"
repository-file: "./repository/repository.db"
http-server:
  address: "localhost:8080"
  timeout: 5s
  idle_timeout: 60s
logger:
  format: "text"         # "text", "json"
  destination: "console" # "console", "file"
  destination-file: ""   # filename if destination = "file"
  level: "debug"         # "debug", "info"
  add_source: false
logger:
  format: "text"         # "text", "json"
  destination: "console" # "console", "file"
  destination-file: ""   # filename if destination = "file"
  level: "debug"         # "debug", "info"
  add_source: false